
#Deployment maneja pods y replica sets
apiVersion: apps/v1
kind: Deployment  
metadata:
  namespace: edwinast-dev
  name: ms2
  labels:
    app: ms2
    areanegocio: pagos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
        - name: ms2
          image: edwinast/ms2:{{ imageTag }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: ms2
            - secretRef:
                name: ms2
          startupProbe:
            httpGet:
              path: /startup
              port: 3000
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 3000
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            initialDelaySeconds: 5          
---
apiVersion: v1
kind: Service
metadata:
  namespace: edwinast-dev
  name: ms2
spec:
  selector:
    app: ms2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: edwinast-dev
  name: ms2
data:
  LOG_LEVEL: "debug"
  PAYMENTS_SERVICE_URL: "http://ms1.edwinast-dev.svc.cluster.local:3000/users"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: edwinast-dev
  name: ms2
data:
  DATABASE_PASSWORD: U3VwZXJTZWd1cm8yMDI1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: edwinast-dev
  name: ms2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms2
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization ## EN BASE AL REQUEST
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization ## EN BASE AL REQUEST
          averageUtilization: 90

            